import Head from 'next/head'
import { ProductList } from '../lib/components/products/product-list'
import { CategoryList } from '../lib/components/categories/category-list'
import { IconHome, IconUserCircle, IconNotification, IconPackage, IconShoppingCart, IconUser, IconX, IconBrandFacebook, IconBrandInstagram, IconBrandTiktok, IconBrandYoutube } from '@tabler/icons'
import { Pagination } from 'swiper';
import { Swiper, SwiperSlide } from 'swiper/react';
import { Menu, Dialog, Transition, Tab } from '@headlessui/react'
import { Fragment, useState, useEffect } from 'react'
import { ChevronDownIcon } from '@heroicons/react/solid'

export function Index({product, category, topbanner, testimonies}) {
  let [loginModal, loginIsOpen] = useState(false);
  let [registerModal, registerIsOpen] = useState(false);
  

  function closeModal() {
    loginIsOpen(false)
    registerIsOpen(false)
  }

  function openLogin() {
    registerIsOpen(false)
    loginIsOpen(true)
  }

  function openRegister() {
    loginIsOpen(false)
    registerIsOpen(true)
  }

  function classNames(...classes) {
    return classes.filter(Boolean).join(' ')
  }

  let [registerTab] = useState({
    'Become Reseller': [],
    'Become Member': []
  })

  const [productModule, productIsActive] = useState(false);
  const [profileModule, profileIsActive] = useState(false);
  const [selectedMenu, setMenu] = useState('home')

  useEffect(() => {
    //make function to call the classes
    checkMenu();
  
    //if nothing to return just put {} or just remove the return
    return () => {
    }
  }, [selectedMenu])

  function checkMenu() {
    productIsActive(false)
    profileIsActive(false)
    // checking menu
    if(selectedMenu === 'product') productIsActive(true)
    if(selectedMenu === 'profile') profileIsActive(true)
  }
  
  
  function openProduct() {
    profileIsActive(false)
    productIsActive(true)
  }

  function openProfile() {
    productIsActive(false)
    profileIsActive(true)
  }
  
  function closeModule(){
    profileIsActive(false)
    productIsActive(false)
    menuIsSelected(false)
  }

  function openMenu(category) {
    setMenu(category);
    
  }


  return (
    <>
      <Head>
        <title>Annona</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Dropdown to select outlet */}
      <div className="z-40 fixed w-full h-14 top-0 left-0 bg-teal-900 text-white pl-4">
        <div className="container h-14 max-w-none md:max-w-lg mx-auto relative flex items-center">
          <Menu as="div" className="relative inline-block text-left">
            <div>
              <Menu.Button className="inline-flex w-full justify-center text-sm font-medium text-white hover:bg-opacity-30 focus:outline-none focus-visible:ring-2 focus-visible:ring-white focus-visible:ring-opacity-75 md:rounded-md md:bg-black md:bg-opacity-20 md:px-4 md:py-2">
                My Shop
                <ChevronDownIcon
                  className="ml-2 -mr-1 h-5 w-5 text-violet-200 hover:text-violet-100"
                  aria-hidden="true"
                />
              </Menu.Button>
            </div>
            <Transition
              as={Fragment}
              enter="transition ease-out duration-100"
              enterFrom="transform opacity-0 scale-95"
              enterTo="transform opacity-100 scale-100"
              leave="transition ease-in duration-75"
              leaveFrom="transform opacity-100 scale-100"
              leaveTo="transform opacity-0 scale-95"
            >
              <Menu.Items className="absolute left-0 mt-2 w-56 origin-top-right divide-y divide-gray-100 rounded-md bg-white shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none">
                <div className="px-1 py-1 ">
                  <Menu.Item>
                    {({ active }) => (
                      <button
                        className={`${
                          active ? 'bg-teal-900 text-white' : 'text-gray-900'
                        } group flex w-full items-center rounded-md px-2 py-2 text-sm`}
                      >
                        My Shop
                      </button>
                    )}
                  </Menu.Item>
                  <Menu.Item>
                    {({ active }) => (
                      <button
                        className={`${
                          active ? 'bg-teal-900 text-white' : 'text-gray-900'
                        } group flex w-full items-center rounded-md px-2 py-2 text-sm`}
                      >
                        Kota Kinabalu
                      </button>
                    )}
                  </Menu.Item>
                  <Menu.Item>
                    {({ active }) => (
                      <button
                        className={`${
                          active ? 'bg-teal-900 text-white' : 'text-gray-900'
                        } group flex w-full items-center rounded-md px-2 py-2 text-sm`}
                      >
                        Sibu
                      </button>
                    )}
                  </Menu.Item>
                </div>
              </Menu.Items>
            </Transition>
          </Menu>
          <div className="absolute w-14 h-14 top-0 right-10 flex items-center justify-center" onClick={openLogin}>
            <IconUser/>
          </div>
          <div className="absolute w-12 h-14 top-0 right-0 flex items-center justify-center">
            <IconShoppingCart/>
          </div>
        </div>
      </div>

      {/* Modal to Login */}
      <Transition appear show={loginModal} as={Fragment}>
        <Dialog as="div" className="relative z-50" onClose={closeModal}>
          <Transition.Child
            as={Fragment}
            enter="ease-out duration-300"
            enterFrom="opacity-0"
            enterTo="opacity-100"
            leave="ease-in duration-200"
            leaveFrom="opacity-100"
            leaveTo="opacity-0"
          >
            <div className="fixed inset-0 bg-black bg-opacity-25" />
          </Transition.Child>

          <div className="fixed inset-0 overflow-y-auto">
            <div className="flex min-h-full items-center justify-center p-4 text-center">
              <Transition.Child
                as={Fragment}
                enter="ease-out duration-300"
                enterFrom="opacity-0 scale-95"
                enterTo="opacity-100 scale-100"
                leave="ease-in duration-200"
                leaveFrom="opacity-100 scale-100"
                leaveTo="opacity-0 scale-95"
              >
                <Dialog.Panel className="w-full max-w-md transform overflow-hidden rounded-2xl bg-white p-6 pb-4 text-left align-middle shadow-xl transition-all bg-gray-50">
                  <Dialog.Title as="h3" className="text-xl font-medium leading-6 text-teal-900">
                    Login
                    <span className="float-right">
                      <IconX className="text-gray-500" onClick={closeModal}></IconX>
                    </span>
                  </Dialog.Title>
                  <div className="">
                      <div className="relative mt-4">
                        <div className="mb-1 text-sm text-gray-600 font-medium">
                          Username
                        </div>
                        <input type="text" className="h-11 px-2 w-full rounded border bg-white focus:outline-none"></input>
                      </div>
                      <div className="relative mt-4">
                        <div className="mb-1 text-sm text-gray-600 font-medium">
                          Password
                        </div>
                        <input type="text" className="h-11 px-2 w-full rounded border bg-white focus:outline-none"></input>
                      </div>
                      <div className="mt-4">
                        <button
                          type="button"
                          className="w-full rounded border border-transparent bg-teal-900 p-3 text-sm font-medium text-white ease-in-out duration-200 hover:bg-teal-700 focus:outline-none focus-visible:ring-2 focus-visible:ring-teal-500 focus-visible:ring-offset-2"
                          onClick={closeModal}
                        >
                          Login
                        </button>
                      </div>
                      <div className="text-sm mt-3">
                          Become a Member? <span className="text-orange-700 font-medium cursor-pointer ease-in-out duration-200 hover:text-orange-500 hover:underline underline-offset-2" onClick= {openRegister}>Click Here</span>
                      </div>
                  </div>
                </Dialog.Panel>
              </Transition.Child>
            </div>
          </div>
        </Dialog>
      </Transition>

      {/* Modal to Register */}
      <Transition appear show={registerModal} as={Fragment}>
        <Dialog as="div" className="relative z-50" onClose={closeModal}>
          <Transition.Child
            as={Fragment}
            enter="ease-out duration-300"
            enterFrom="opacity-0"
            enterTo="opacity-100"
            leave="ease-in duration-200"
            leaveFrom="opacity-100"
            leaveTo="opacity-0"
          >
            <div className="fixed inset-0 bg-black bg-opacity-25" />
          </Transition.Child>
          <div className="fixed inset-0 overflow-y-auto">
            <div className="flex min-h-full items-center justify-center p-4 text-center">
              <Transition.Child
                as={Fragment}
                enter="ease-out duration-300"
                enterFrom="opacity-0 scale-95"
                enterTo="opacity-100 scale-100"
                leave="ease-in duration-200"
                leaveFrom="opacity-100 scale-100"
                leaveTo="opacity-0 scale-95"
              >
                <Dialog.Panel className="w-full max-w-md transform overflow-hidden rounded-2xl bg-white p-6 text-left align-middle shadow-xl transition-all">
                <Dialog.Title as="h3" className="text-xl font-medium leading-6 text-teal-900">
                    Register
                    <span className="float-right">
                      <IconX className="text-gray-500" onClick={closeModal}></IconX>
                    </span>
                </Dialog.Title>
                <Tab.Group>
                  <Tab.List className="flex space-x-1 rounded bg-blue-900/20 p-1 mt-4">
                      {Object.keys(registerTab).map((register) => (
                      <Tab
                        key={register}
                        className={({ selected }) =>
                          classNames(
                            'w-full rounded py-2.5 text-sm font-medium leading-5 text-teal-900 ease-in-out duration-200',
                            'ring-white ring-opacity-60 ring-offset-2 ring-offset-teal-400 focus:outline-none',
                            selected
                              ? 'bg-white shadow'
                              : 'text-teal-700 ease-in-out duration-200 hover:bg-white/[0.12] hover:text-teal-900'
                          )
                        }
                      >
                      {register}
                      </Tab>
                    ))}
                  </Tab.List>
                  <Tab.Panels>
                    <Tab.Panel>
                      <div className="mt-4 text-lg leading-6 font-bold">
                        Annona Business Owner
                      </div>
                      <p className="mt-2 text-sm text-gray-800">
                        Start a low-cost, low-risk business. Enjoy the income and reward when you grow your business. 
                      </p>
                      <div className="">
                          <div className="mt-4">
                            <div className="mb-1 text-sm text-gray-500 font-medium">
                              Full Name
                            </div>
                            <input type="text" className="h-11 px-2 w-full rounded border bg-white focus:outline-none"></input>
                          </div>
                          <div className="mt-4">
                            <div className="mb-1 text-sm text-gray-500 font-medium">
                              Phone No.
                            </div>
                            <div className="grid grid-cols-3 gap-2">
                              <select className="h-11 px-2 w-full rounded border bg-white focus:outline-none">
                                <option value="">+60</option>
                                <option value="">+61</option>
                                <option value="">+62</option>
                              </select>
                              <input type="text" className="h-11 px-2 w-full rounded border bg-white focus:outline-none col-span-2"></input>
                            </div>
                          </div>
                          <div className="mt-4">
                            <div className="mb-1 text-sm text-gray-500 font-medium">
                              Email
                            </div>
                            <input type="text" className="h-11 px-2 w-full rounded border bg-white focus:outline-none"></input>
                          </div>
                          <div className="mt-4">
                            <div className="mb-1 text-sm text-gray-500 font-medium">
                              Date of Birth
                            </div>
                            <div className="grid grid-cols-3 gap-2">
                              <select className="h-11 px-2 w-full rounded border bg-white focus:outline-none">
                                <option value="">Day</option>
                              </select>
                              <select className="h-11 px-2 w-full rounded border bg-white focus:outline-none">
                                <option value="">Month</option>
                              </select>
                              <select className="h-11 px-2 w-full rounded border bg-white focus:outline-none">
                                <option value="">Year</option>
                              </select>
                            </div>
                          </div>
                          <div className="mt-4">
                            <div className="mb-1 text-sm text-gray-500 font-medium">
                              Package
                            </div>
                            <select className="h-11 px-2 w-full rounded border bg-white focus:outline-none">
                                <option value="">Annona Bronze Consultant - ABC</option>
                              </select>
                          </div>
                          <p className="mt-4 text-sm text-gray-800 italic font-medium">
                          Your credentials will be sent to your Email or mobile please ensure you key in a valid email or mobile.
                          </p>
                      </div>
                      <div className="mt-4">
                        <button
                          type="button"
                          className="w-full rounded border border-transparent bg-teal-900 p-3 text-sm font-medium text-white ease-in-out duration-200 hover:bg-teal-700 focus:outline-none focus-visible:ring-2 focus-visible:ring-teal-500 focus-visible:ring-offset-2"
                          onClick={closeModal}
                        >
                          Register Now
                        </button>
                        <div className="text-sm mt-5">
                            Already have account? <span className="text-orange-700 font-medium cursor-pointer ease-in-out duration-200 hover:text-orange-500 hover:underline underline-offset-2" onClick= {openLogin}>Login Here</span>
                        </div>
                      </div>
                    </Tab.Panel>
                    <Tab.Panel>   
                      <div className="mt-4 text-lg leading-6 font-bold">
                          Annona Privileged Customer Programme
                        </div>
                        <p className="mt-2 text-sm text-gray-800">
                          Buy quality Annona products at member’s price, earn points and enjoy special privileges.
                        </p>
                        <div className="">
                          <div className="mt-4">
                            <div className="mb-1 text-sm text-gray-500 font-medium">
                              Full Name
                            </div>
                            <input type="text" className="h-11 px-2 w-full rounded border bg-white focus:outline-none"></input>
                          </div>
                          <div className="mt-4">
                            <div className="mb-1 text-sm text-gray-500 font-medium">
                              Phone No.
                            </div>
                            <div className="grid grid-cols-3 gap-2">
                              <select className="h-11 px-2 w-full rounded border bg-white focus:outline-none">
                                <option value="">+60</option>
                                <option value="">+61</option>
                                <option value="">+62</option>
                              </select>
                              <input type="text" className="h-11 px-2 w-full rounded border bg-white focus:outline-none col-span-2"></input>
                            </div>
                          </div>
                          <div className="mt-4">
                            <div className="mb-1 text-sm text-gray-500 font-medium">
                              Email
                            </div>
                            <input type="text" className="h-11 px-2 w-full rounded border bg-white focus:outline-none"></input>
                          </div>
                          <div className="mt-4">
                            <div className="mb-1 text-sm text-gray-500 font-medium">
                              Date of Birth
                            </div>
                            <div className="grid grid-cols-3 gap-2">
                              <select className="h-11 px-2 w-full rounded border bg-white focus:outline-none">
                                <option value="">Day</option>
                              </select>
                              <select className="h-11 px-2 w-full rounded border bg-white focus:outline-none">
                                <option value="">Month</option>
                              </select>
                              <select className="h-11 px-2 w-full rounded border bg-white focus:outline-none">
                                <option value="">Year</option>
                              </select>
                            </div>
                          </div>
                          <div className="mt-4">
                            <div className="mb-1 text-sm text-gray-500 font-medium">
                              Package
                            </div>
                            <select className="h-11 px-2 w-full rounded border bg-white focus:outline-none">
                                <option value="">Annona Bronze Consultant - ABC</option>
                              </select>
                          </div>
                          <p className="mt-4 text-sm text-gray-800 italic font-medium">
                          Your credentials will be sent to your Email or mobile please ensure you key in a valid email or mobile.
                          </p>
                      </div>
                      <div className="mt-4">
                        <button
                          type="button"
                          className="w-full rounded border border-transparent bg-teal-900 p-3 text-sm font-medium text-white ease-in-out duration-200 hover:bg-teal-700 focus:outline-none focus-visible:ring-2 focus-visible:ring-teal-500 focus-visible:ring-offset-2"
                          onClick={closeModal}
                        >
                          Register Now
                        </button>
                        <div className="text-sm mt-5">
                            Already have account? <span className="text-orange-700 font-medium cursor-pointer ease-in-out duration-200 hover:text-orange-500 hover:underline underline-offset-2" onClick= {openLogin}>Login Here</span>
                        </div>
                      </div>
                    </Tab.Panel>
                  </Tab.Panels>
                </Tab.Group>
                </Dialog.Panel>
              </Transition.Child>
            </div>
          </div>
        </Dialog>
      </Transition>
      
      <div className="container bg-gray-50 max-w-none md:max-w-lg mx-auto pt-14 pb-20">
        <Swiper
            modules={[Pagination]}
            spaceBetween={50}
            slidesPerView={1}
            pagination={true}
          >  
            { topbanner.map((slider) => 
              <SwiperSlide key= { slider.id }><img src={ slider.image }></img></SwiperSlide>
            )}
        </Swiper>
        <div className="px-4">
            <CategoryList categories= { category }/>
            <ProductList products= { product }/>

            {/* About Us */}
            <div className="mt-8 mb-2 font-bold text-teal-900">
                About Annona
            </div>
            <p className="leading-6">
              ANNONA highlights research - based beauty and health solutions to meet the needs of consumers. Founded under MOS Nutraceutical Sdn. Bhd. by Puan Ony Nurhusni and Encik Syahril Izwan, ANNONA is dedicated and committed to expand health and beauty awareness to the community through various products under ANNONA brand.
            </p>
            <img src="/img/aboutus.jpg" className="w-full mt-4"></img>
            
            {/* Testimony */}
            <div className="mt-8 mb-2 font-bold text-teal-900">
                Testimony
            </div>
            <Swiper className="mt-4"
              modules={[Pagination]}
              spaceBetween={50}
              slidesPerView={1}
              pagination={true}
            >  
              { testimonies.map((testimony) => 
                <SwiperSlide key= { testimony.id }><img src={ testimony.image }></img></SwiperSlide>
              )}
            </Swiper>

            {/* Testimony */}
            <div className="mt-8 font-bold text-teal-900">
                Follow Us
            </div>
            <div className="mt-2 flex">
                <a href="" target="_blank" className="mr-2 text-gray-600 ease-in-out duration-200 hover:text-teal-900"><IconBrandFacebook></IconBrandFacebook></a>
                <a href="" target="_blank" className="mr-2 text-gray-600 ease-in-out duration-200 hover:text-teal-900"><IconBrandInstagram></IconBrandInstagram></a>
                <a href="" target="_blank" className="mr-2 text-gray-600 ease-in-out duration-200 hover:text-teal-900"><IconBrandTiktok></IconBrandTiktok></a>
                <a href="" target="_blank" className="mr-2 text-gray-600 ease-in-out duration-200 hover:text-teal-900"><IconBrandYoutube></IconBrandYoutube></a>
            </div>

            {/* Legal */}
            <div className="mt-8 font-bold text-teal-900">
                Legal
            </div>
            <div className="mt-2">
                <a href="" target="_blank" className="mr-2 text-gray-600 ease-in-out duration-200 hover:text-teal-900">Terms and Conditions</a>
                <br></br>
                <a href="" target="_blank" className="mr-2 text-gray-600 ease-in-out duration-200 hover:text-teal-900">Privacy Policy</a>
                <br></br>
                <a href="" target="_blank" className="mr-2 text-gray-600 ease-in-out duration-200 hover:text-teal-900">Copyright Information</a>
            </div>
        </div>
      </div>

      {/* Bottom Menu */}
      <div className="z-40 fixed w-full h-16 bottom-0 left-0 bg-white border-t grid grid-cols-4">
        <div className={`h-16 flex flex-col items-center justify-center ease-in-out duration-200  ${selectedMenu === 'home' ? 'text-teal-900' : 'text-gray-400'}`} onClick={ () => setMenu('home') }>
          <IconHome className=""/>
          <span className="text-sm">Home</span>
        </div>
        <div className={`h-16 flex flex-col items-center justify-center ease-in-out duration-200 ${selectedMenu === 'product' ? 'text-teal-900' : 'text-gray-400'}`} onClick={ () => setMenu('product') }>
          <IconPackage className=""/>
          <span className="text-sm">Product</span>
        </div>
        <div className="h-16 flex flex-col items-center justify-center ease-in-out duration-200 text-gray-400">
          <IconNotification className=""/>
          <span className="text-sm">Announce</span>
        </div>
        <div className={`h-16 flex flex-col items-center justify-center ease-in-out duration-200 ${selectedMenu === 'profile' ? 'text-teal-900' : 'text-gray-400'}`} onClick={ () => setMenu('profile') }>
          <IconUserCircle className=""/>
          <span className="text-sm">Me</span>
        </div>
      </div>
      

      {/* Product Module */}
      <Transition
        show={ productModule }
        enter="transition ease-in-out duration-200 transform"
        enterFrom="translate-x-full"
        enterTo="translate-x-0"
        leave="transition ease-in-out duration-100 transform"
        leaveFrom="translate-x-0"
        leaveTo="translate-x-full"
        className="fixed w-full h-full top-0 translate-x-full bg-gray-50 z-30 pt-14"
      >
        <div>
          Product module
        </div>
      </Transition>

      {/* Profile Module */}
      <Transition
        show={ profileModule }
        enter="transition ease-in-out duration-200 transform"
        enterFrom="translate-x-full"
        enterTo="translate-x-0"
        leave="transition ease-in-out duration-100 transform"
        leaveFrom="translate-x-0"
        leaveTo="translate-x-full"
        className="fixed w-full h-full top-0 translate-x-full bg-gray-50 z-30 pt-14"
      >
        <div>
          profile Module
        </div>
      </Transition>
      
    </>
  )
}

export default Index;

// export function profile(){
//   return (
//     <>
//       <div appear show={profileModule} as={Fragment} className="fixed w-full h-full top-0 left-0 bg-white">
//         asd
//       </div>
//     </>
//   )
// }

//getStaticProps use to create static API data
export function getStaticProps() {
  //create the array object API to show it to interface
  const product = [
    {
      id: '1',
      name: 'CETAPHIL GENTLE SKIN CLEANSER (ALL SKIN TYPE ALL FACE TYPE)',
      retail_price: '34.20',
      member_price: '38.70',
      purchase_value: '38.70',
      image: '/img/product-1.jpg',
      stock: 10,
    },
    {
      id: '2',
      name: 'Product Name Here',
      retail_price: '54.50',
      member_price: '59.50',
      purchase_value: '59.50',
      image: '/img/product-2.jpg',
      stock: 10,
    },
    {
      id: '3',
      name: 'Product Name Here',
      retail_price: '100.00',
      member_price: '100.00',
      purchase_value: '100.00',
      image: '/img/product-3.jpg',
      stock: 10,
    },
    {
      id: '4',
      name: 'CETAPHIL GENTLE SKIN CLEANSER (ALL SKIN TYPE ALL FACE TYPE)',
      retail_price: '100.00',
      member_price: '100.00',
      purchase_value: '100.00',
      image: '/img/product-4.jpg',
      stock: 10,
    },
    {
      id: '5',
      name: 'CETAPHIL GENTLE SKIN CLEANSER (ALL SKIN TYPE ALL FACE TYPE)',
      retail_price: '100.00',
      member_price: '100.00',
      purchase_value: '100.00',
      image: '/img/product-1.jpg',
      stock: 10,
    },
    {
      id: '6',
      name: 'CETAPHIL GENTLE SKIN CLEANSER (ALL SKIN TYPE ALL FACE TYPE)',
      retail_price: '100.00',
      member_price: '100.00',
      purchase_value: '100.00',
      image: '/img/product-2.jpg',
      stock: 10,
    },
  ]

  const category = [
    {
      id: 1,
      name: 'All Categories',
      image: '/categoryicon/allcategory.png',
    },
    {
      id: 2,
      name: 'A-Annona',
      image: '/categoryicon/a-annona.png',
    },
    {
      id: 3,
      name: 'Adult Supplement',
      image: '/categoryicon/adultsuplement.png',
    },
    {
      id: 4,
      name: 'Baby Care',
      image: '/categoryicon/babycare.png',
    },
    {
      id: 5,
      name: 'Cosmetic',
      image: '/categoryicon/cosmetics.png',
    },
    {
      id: 6,
      name: 'Face Mask',
      image: '/categoryicon/facemask.png',
    },
    {
      id: 7,
      name: 'Kids Supplement',
      image: '/categoryicon/kidssuplement.png',
    },
    {
      id: 8,
      name: 'Medical',
      image: '/categoryicon/medical.png',
    }
  ]

  const topbanner = [
    {
      id: 1,
      image: '/img/banner-1.jpg'
    },
    {
      id: 2,
      image: '/img/banner-2.jpg'
    },
    {
      id: 4,
      image: '/img/banner-4.jpg'
    },
    {
      id: 5,
      image: '/img/banner-5.jpg'
    }
  ]

  const testimonies = [
    {
      id: 1,
      image: '/img/testimony-1.jpg'
    },
    {
      id: 2,
      image: '/img/testimony-2.jpg'
    },
    {
      id: 3,
      image: '/img/testimony-3.jpg'
    },
    {
      id: 4,
      image: '/img/testimony-4.jpg'
    },
    {
      id: 5,
      image: '/img/testimony-5.jpg'
    },
    {
      id: 6,
      image: '/img/testimony-6.jpg'
    },
    {
      id: 7,
      image: '/img/testimony-7.jpg'
    },
    {
      id: 8,
      image: '/img/testimony-8.jpg'
    },
    {
      id: 9,
      image: '/img/testimony-9.jpg'
    },
    {
      id: 10,
      image: '/img/testimony-10.jpg'
    },
    {
      id: 11,
      image: '/img/testimony-11.jpg'
    },
    {
      id: 12,
      image: '/img/testimony-12.jpg'
    },
    {
      id: 13,
      image: '/img/testimony-13.jpg'
    },
    {
      id: 14,
      image: '/img/testimony-14.jpg'
    }
  ]

  //after create the object API, make sure to return it so it can pass to interface
  return {
		props: {
			product, category, topbanner, testimonies
		}
	}
}